apiVersion: v1
kind: Pod
metadata:
  name: nginx-persistent-pod
  labels:
    app: nginx-persistent
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: web-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-storage
    hostPath:
      path: /run/desktop/mnt/host/c/PROJECTS/docker_kubernetes/module5_storage_volumes/html
      type: DirectoryOrCreate
