apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-db
  template:
    metadata:
      labels:
        app: banking-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: "bankpass"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: banking-db-svc
spec:
  selector:
    app: banking-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
