apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-frontend
  template:
    metadata:
      labels:
        app: banking-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: static-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: static-content
        hostPath:
          path: /run/desktop/mnt/host/c/PROJECTS/docker_kubernetes/module10_projects/p1_banking/src/frontend
---
apiVersion: v1
kind: Service
metadata:
  name: banking-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: banking-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
